#!/bin/bash

docker-compose exec --user=www-data -e https_proxy=$http_proxy -e http_proxy=$http_proxy php bash -c "composer install"

docker-compose exec --user=www-data -e http_proxy=$http_proxy -e http_proxy=$http_proxy php bash -c \
    "sudo chown -R www-data:www-data /home/www-data \
    && npm config set proxy $http_proxy \
    && yarn install --production=false \
    && yarn dev"

docker-compose exec --user=www-data -e https_proxy=$http_proxy -e http_proxy=$http_proxy php bash -c \
    "./bin/console doctrine:migrations:migrate --quiet --allow-no-migration"