version: '3'
services:
  db:
    image: mysql:5.6
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

  redis:
    image: redis:4.0.2
    restart: unless-stopped
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis/data:/data
    command: 'redis-server /usr/local/etc/redis/redis.conf'
    ports:
      - ${REDIS_PORT}:6379

  php:
    build:
     context: php
     args:
      HTTP_PROXY: ${HTTP_PROXY}
    links:
      - db
    ports:
      - ${PHP_PORT}:9000
    volumes:
      - ${APP_PATH}:/var/www/vipcorp
    working_dir: /var/www/vipcorp

  webserver:
    image: nginx:1.11
    depends_on:
      - php
    volumes:
      - ${APP_PATH}:/var/www/vipcorp
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/data:/var/log/nginx
    ports:
      - ${APP_WEB_PORT}:80

  elk:
    image: willdurand/elk
    ports:
      - ${KIBANA_PORT}:80
    depends_on:
      - php
      - webserver
    volumes:
      - ./elk/logstash:/etc/logstash:cached
      - ./elk/logstash/patterns:/opt/logstash/patterns:cached
      - ${APP_PATH}:/var/www/vipcorp
      - ./nginx/data:/var/log/nginx